### ISSUE TITLE
can't untar/unzip amos.tar.gz

### ISSUE THREAD

**Issue by Khoa-NT** [NMontanaBrown/saramis#5]
Hello, thank you for releasing the dataset.

I can untar/unzip the file `total.tar.gz`; however, I can't untar/unzip `amos.tar.gz` in my Ubuntu. 
(Sadly, `abdomen.tar.gz` is too large for my current storage, so I can't test it.)

Can you check the `amos.tar.gz` again?
Thanks

**Comment by NMontanaBrown** [comment]
Hi @Khoa-NT - apologies for the inconvenience. I'm on leave this week but have set myself a reminder to fix this when I get back. Will ping once it's done and thanks for flagging!

**Comment by NMontanaBrown** [comment]
Hi @Khoa-NT this has now been patched: https://huggingface.co/datasets/NMontanaBrown/saramis_amos/tree/main

Let me know if you have any issues!
