### ISSUE TITLE
data download fails

### ISSUE THREAD

**Issue by jywu511** [NMontanaBrown/saramis#6]
![image](https://github.com/NMontanaBrown/saramis/assets/91044076/728767b7-87d6-4164-ba11-e91b403aace8)

**Comment by NMontanaBrown** [comment]
Patching this tomorrow - will post new links here once ready @jywu511

**Comment by NMontanaBrown** [comment]
Hi @jywu511 I'm migrating the dataset to HuggingFace for simplicity: https://huggingface.co/datasets/NMontanaBrown/saramis_abdomen/tree/main

The full datasets are uploading now and should be fully live in the next few days in totality. I'll tag you once it's finished.

**Comment by jywu511** [comment]
Thanks for your reply! A fantastic work!

**Comment by NMontanaBrown** [comment]
@jywu511 this should now patched - let me update the docs to point to the correct locations! 

https://huggingface.co/datasets/NMontanaBrown/saramis_abdomen/tree/main
